baseURL = "/"
languageCode = "en-us"
title = "Container Technology Wiki"

disablePathToLower = true 


[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = "trac" # manni perldoc  monokai  igor xcode vim autumn  vs rrt borland native colorful  default murphy trac tango fruity bw emacs pastie friendly 
    tabWidth = 4

[markup.goldmark.renderer]
unsafe= true


[params]
logo = "images/logo.png"
mail = "info@companyname.com"
mobile = "1234565523"
# Meta data
description = "The developer and DevOps resource center for container technology, architecture, security and orchestration."


